/*
Generated by UnityTwine on 2/22/2016 12:14:49 AM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class digm530_tweeExport: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
	}
    
	// .............
	// #0: StoryTitle

	void passageInit_0()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"digm530-awt");	
	}
    
	// .............
	// #1: Intro

	void passageInit_1()
	{
		this.Passages["Intro"] = new TwinePassage("Intro", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"Your world slowly fades to black as you utter your last words:");
		yield return new TwineText(@"<br>");
		yield return new TwineText(@"<p>");
		yield return new TwineText(@"(print: ""..."" + $epitaph)");
		yield return new TwineText(@"</p>");
		yield return new TwineText(@"");
		yield return new TwineText(@"# ");yield return new TwineLink(@"You Die ", @"You Die ", @" wakeUp", null, null);	
	}
    
	// .............
	// #2: Narrator Intro

	void passageInit_2()
	{
		this.Passages["Narrator Intro"] = new TwinePassage("Narrator Intro", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"''NARRATOR ONLY''");
		yield return new TwineText(@"");
		yield return new TwineText(@"A character is just about to utter their last words:");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Their final words... ", @"Their final words... ", @" finalWords", null, null);	
	}
    
	// .............
	// #3:  finalWords

	void passageInit_3()
	{
		this.Passages[" finalWords"] = new TwinePassage(" finalWords", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"(set: $epitaph to (prompt: ""Their final words were:""))");
		yield return new TwineText(@"");
		yield return new TwineText(@"(display: ""Intro"")");	
	}
    
	// .............
	// #4:  wakeUp

	void passageInit_4()
	{
		this.Passages[" wakeUp"] = new TwinePassage(" wakeUp", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"You open your eyes, slowly. The phrase ""(print: $epitaph)"" seems burned into your mind.");
		yield return new TwineText(@"");
		yield return new TwineText(@"What was that? What does (print: $epitaph) mean? You were certain you just died. Yet you remember virtually nothing. Not even where you are.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You are surrounded by a void. An endless tunnel in all directions. Nothing but darkness except for a light fixed on the horizon. No matter which way you turn the light seems infinitely far away.");
		yield return new TwineText(@"");
		yield return new TwineText(@"As you regain your consciousness you feel something in your hand.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Something familiar.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You firmly grasp what seems to be a handle. It seemingly restores your strength. You look to your hand and see your trusty...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Staff ", @"Staff ", @" staffRoom", null, null);
		yield return new TwineLink(@"Longsword ", @"Longsword ", @" swordRoom", null, null);
		yield return new TwineLink(@"Crossbow ", @"Crossbow ", @" crossbowRoom", null, null);	
	}
    
	// .............
	// #5:  staffRoom

	void passageInit_5()
	{
		this.Passages[" staffRoom"] = new TwinePassage(" staffRoom", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"The world springs up around you. You and your trusty staff.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Suddenly details spring back to your mind. You were in your hut, practicing your magic spells. When... when, well--that's all you remember for now.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But suddenly around you the world springs to life. Some of the black void is filled in with what you remember to be your druidic hut.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Beyond your hut a magical glade forms seeping with magic and teeming with all sorts of life.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your strength returns to you and clasp your staff to your chest.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interlude01", null, null);
		yield return new TwineText(@"(set: $weapon to ""staff"")");	
	}
    
	// .............
	// #6:  swordRoom

	void passageInit_6()
	{
		this.Passages[" swordRoom"] = new TwinePassage(" swordRoom", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"All around you the world falls into place. From the infinite void what is unquestionably castle stone begins to surround you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"This place is familiar to you. Your royal chambers. And in your hand is the sword with which you liberated a kingdom.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The large cold room is accented only by a grand fireplace and a magnificent chandeleir hanging above your bed. Many details in the room still fall endlessly into a black void. Though where the cold castle ends and the black void begins is anyone's guess.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interlude01", null, null);
		yield return new TwineText(@"(set: $weapon to ""sword"")");	
	}
    
	// .............
	// #7:  crossbowRoom

	void passageInit_7()
	{
		this.Passages[" crossbowRoom"] = new TwinePassage(" crossbowRoom", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"As your hand wraps around the familiar grip of your grossbow you slowly blink.");
		yield return new TwineText(@"");
		yield return new TwineText(@"As your eyes open you find yourself in a changed landscape. You were a hunter.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Adorned around the room are trophies from your various escapades. Above your bed is the frame of a mighty bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"A roaring fire is ablaze in a pit in the middle of the room. A window to peer outside is visible and a roaring blizzard is seen outside.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interlude01", null, null);
		yield return new TwineText(@"(set: $weapon to ""bow"")");	
	}
    
	// .............
	// #8:  interlude01

	void passageInit_8()
	{
		this.Passages[" interlude01"] = new TwinePassage(" interlude01", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"''NARRATOR ONLY''");
		yield return new TwineText(@"");
		yield return new TwineText(@"All is not well for our developing character. A challenge confronts them:");
		yield return new TwineText(@"");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineLink(@"There is a knock on the door ", @"There is a knock on the door ", @" knockStaff ", null, null);
		yield return new TwineLink(@"There is a growl outside ", @"There is a growl outside ", @" growlStaff ", null, null);
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineLink(@"There is a knock on the door ", @"There is a knock on the door ", @" knockSword ", null, null);
		yield return new TwineLink(@"There is a growl outside ", @"There is a growl outside ", @" growlSword ", null, null);
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineLink(@"There is a knock on the door ", @"There is a knock on the door ", @" knockBow ", null, null);
		yield return new TwineLink(@"There is a growl outside ", @"There is a growl outside ", @" growlBow ", null, null);
		yield return new TwineText(@"]");	
	}
    
	// .............
	// #9:  knockStaff 

	void passageInit_9()
	{
		this.Passages[" knockStaff "] = new TwinePassage(" knockStaff ", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"A series of knocks is heard on your hut's door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Strange, these woods are home only to a few creatures. None of which would typically knock. Growl, snarl, or purr perhaps--but never knock.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You grip your staff, knowing that should the worst happen you can cast a spell to save yourself.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But what of ""(print: $epitaph)"" the phrase sticks out to you like a bad omen. Surely these knocks are a bad sign.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Ignore The Knock ", @"Ignore The Knock ", @" ignore01", null, null);
		yield return new TwineLink(@"Open The Door ", @"Open The Door ", @" door01", null, null);
		yield return new TwineLink(@"Peek Out Your Window ", @"Peek Out Your Window ", @" window01", null, null);
		yield return new TwineText(@"(set: $challenge to ""knock"")");	
	}
    
	// .............
	// #10:  growlStaff 

	void passageInit_10()
	{
		this.Passages[" growlStaff "] = new TwinePassage(" growlStaff ", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"There's a terrifying growl outside your druidic hut.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It could be virtually anything. Your fears run wild--it could be a humongous python, a hideous bandersnatch, or it could be a harmless kitten.");
		yield return new TwineText(@"");
		yield return new TwineText(@"And then there's the matter of whatever ""(print: $epitaph)"" means.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Hide under the bed ", @"Hide under the bed ", @" bed01", null, null);
		yield return new TwineLink(@"Ready your (print: $weapon) ", @"Ready your (print: $weapon) ", @" ready01", null, null);
		yield return new TwineLink(@"Scream for Help ", @"Scream for Help ", @" scream01", null, null);
		yield return new TwineText(@"(set: $challenge to ""growl"")");	
	}
    
	// .............
	// #11:  knockSword 

	void passageInit_11()
	{
		this.Passages[" knockSword "] = new TwinePassage(" knockSword ", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"The royal chambers are hardly ever disturbed. Your majesty is only bothered by events of utmost importance. Yet a knock is heard on your door all the same.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Impulsively you begin to rush towards the door but you remember the phrase lingering in your mind.");
		yield return new TwineText(@"");
		yield return new TwineText(@"(print: $epitaph)");
		yield return new TwineText(@"");
		yield return new TwineText(@"What to do?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Ignore The Knock ", @"Ignore The Knock ", @" ignore01", null, null);
		yield return new TwineLink(@"Open The Door ", @"Open The Door ", @" door01", null, null);
		yield return new TwineLink(@"Peek Out Your Window ", @"Peek Out Your Window ", @" window01", null, null);
		yield return new TwineText(@"(set: $challenge to ""knock"")");	
	}
    
	// .............
	// #12:  growlSword 

	void passageInit_12()
	{
		this.Passages[" growlSword "] = new TwinePassage(" growlSword ", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"You hear a deep roaring growl outside your chamber.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The last time this happened your grandmother had a dragon almost melt your face.");
		yield return new TwineText(@"");
		yield return new TwineText(@"In all honesty the only animal that should make it up to your tower is a cat but in your kingdom you never know.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Not to mention ""(print: $epitaph)"" still makes no sense to you. ");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Hide under the bed ", @"Hide under the bed ", @" bed01", null, null);
		yield return new TwineLink(@"Ready your (print: $weapon) ", @"Ready your (print: $weapon) ", @" ready01", null, null);
		yield return new TwineLink(@"Scream for Help ", @"Scream for Help ", @" scream01", null, null);
		yield return new TwineText(@"(set: $challenge to ""growl"")");	
	}
    
	// .............
	// #13:  knockBow 

	void passageInit_13()
	{
		this.Passages[" knockBow "] = new TwinePassage(" knockBow ", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"Time passes slowly as all you hear are the crackles of flames and the soft blowing wind outside.");
		yield return new TwineText(@"");
		yield return new TwineText(@"A set of knocks suddenly pierces the serenity. Who, or what, could be knocking on your door. A secluded hunter knows only a few select friends.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Meanwhile, in the back of your mind, (print: $epitaph) remains a complete mystery. Why is this phrase so important? Why do you think you are dead?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Ignore The Knock ", @"Ignore The Knock ", @" ignore01", null, null);
		yield return new TwineLink(@"Open The Door ", @"Open The Door ", @" door01", null, null);
		yield return new TwineLink(@"Peek Out Your Window ", @"Peek Out Your Window ", @" window01", null, null);
		yield return new TwineText(@"(set: $challenge to ""knock"")");	
	}
    
	// .............
	// #14:  growlBow 

	void passageInit_14()
	{
		this.Passages[" growlBow "] = new TwinePassage(" growlBow ", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"More comes rushing back. You chose to live here for the thrill of the hunt. A wild mountain with wild targets.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You hear a growl outside. A deep, snarling growl. Unquestionably the growl is from a terrifying beastie.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Was ""(print: $epitaph)"" a warning? Some sort of foresight? Maybe it would be best not to hunt this beast. But the thrill calls to you as you grip your crossbow tighter and tighter.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Hide under the bed ", @"Hide under the bed ", @" bed01", null, null);
		yield return new TwineLink(@"Ready your (print: $weapon) ", @"Ready your (print: $weapon) ", @" ready01", null, null);
		yield return new TwineLink(@"Scream for Help ", @"Scream for Help ", @" scream01", null, null);
		yield return new TwineText(@"(set: $challenge to ""growl"")");	
	}
    
	// .............
	// #15:  ignore01

	void passageInit_15()
	{
		this.Passages[" ignore01"] = new TwinePassage(" ignore01", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Out of fear you decide to let the knock go unanswered. Choosing instead to stay safely where you are clutching your trusty staff.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Royalty such as yourself should not be bothered by anything. If it is really so important the knocks will happen again.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"The life of seclusion is your only option. Even if there was another person out there in this blizzard, you would allow them to freeze in the cold to continue your hermitage.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeKnock", null, null);
		yield return new TwineText(@"(set: $action to ""ignore"")");	
	}
    
	// .............
	// #16:  door01

	void passageInit_16()
	{
		this.Passages[" door01"] = new TwinePassage(" door01", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"A magic user has nothing to fear. Confidently you stride towards the door.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"As decisively as you saved your kingdom you sheathe your sword and head towards the door.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"The thought of company excites you. Your extended hermitage is unnecessary. You step away from the crackling embers of your fire and move towards the door.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeKnock", null, null);
		yield return new TwineText(@"(set: $action to ""door"")");	
	}
    
	// .............
	// #17:  window01

	void passageInit_17()
	{
		this.Passages[" window01"] = new TwinePassage(" window01", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You are curious, but not so curious to throw caution to the wind. You decide to peek out your window and begin to move towards the window.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Perhaps it's paranoia, but you are compelled to peer outside your window first.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"What in the blazes could be outside?");
		yield return new TwineText(@"");
		yield return new TwineText(@"You decide to sneak a glance outside your window.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeKnock", null, null);
		yield return new TwineText(@"(set: $action to ""door"")");	
	}
    
	// .............
	// #18:  bed01

	void passageInit_18()
	{
		this.Passages[" bed01"] = new TwinePassage(" bed01", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Terrified of fighting and possibly harming a woodland creature you scramble underneath your bed.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"*Nope!* you think to yourself. As you scramble underneath yoru bed.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"No matter what awaits you, the best place to set an ambush is under the bed. You hide underneath your bed of furs.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeGrowl", null, null);
		yield return new TwineText(@"(set: $action to ""bed"")");	
	}
    
	// .............
	// #19:  ready01

	void passageInit_19()
	{
		this.Passages[" ready01"] = new TwinePassage(" ready01", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You clutch your staff in your hand. Battle-ready. Thinking of all manner of spells you might need to combat this most likely *deadly* foe.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Royalty doesn't back down. You grip your sword confidently in your hands. As you grip the sword you feel more alive than ever.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"No matter the beast. You and your crossbow can take down any target no matter how large.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeGrowl", null, null);
		yield return new TwineText(@"(set: $action to ""ready"")");	
	}
    
	// .............
	// #20:  scream01

	void passageInit_20()
	{
		this.Passages[" scream01"] = new TwinePassage(" scream01", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You let out a large bellowing scream. Letting the world know, and the monster outside, that you are absolutely terrified.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Your drop your sword clanking the ground.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""AhhhhahhahhhhhahhahahahhahahahAHHHHHHHHHH!!!!!"" you scream at the top of your lungs. Surely all your attendants will come rushing.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"You unleash a mighty battle-cry at the beast on the other side of your door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)!!!!!!""");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeGrowl", null, null);
		yield return new TwineText(@"(set: $action to ""scream"")");	
	}
    
	// .............
	// #21:  interludeKnock

	void passageInit_21()
	{
		this.Passages[" interludeKnock"] = new TwinePassage(" interludeKnock", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"''NARRATOR ONLY''");
		yield return new TwineText(@"");
		yield return new TwineText(@"The character's doom awaits them. The knock on the door was from none other than...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"A mysterious hooded figure ", @"A mysterious hooded figure ", @" hoodedFigure01", null, null);
		yield return new TwineLink(@"The character's grandmother ", @"The character's grandmother ", @" grandma01", null, null);	
	}
    
	// .............
	// #22:  interludeGrowl

	void passageInit_22()
	{
		this.Passages[" interludeGrowl"] = new TwinePassage(" interludeGrowl", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"''NARRATOR ONLY''");
		yield return new TwineText(@"");
		yield return new TwineText(@"The character's doom awaits them. The source of the growl was none other than...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"A bear ", @"A bear ", @" bearAttack", null, null);
		yield return new TwineLink(@"A cat... that SOUNDS like a bear ", @"A cat... that SOUNDS like a bear ", @" catAttack", null, null);	
	}
    
	// .............
	// #23:  bearAttack

	void passageInit_23()
	{
		this.Passages[" bearAttack"] = new TwinePassage(" bearAttack", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"(if: $action is ""bed"")[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You dash under your bed. Your staff dropping to the floor. Hiding is the best option you think to yourself.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The growls turn into snarls and all of the sudden your front door explodes into splinters. A massive bear comes lumbering into your hut.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear stumbles and sniffs around the room. You realize why the bear is here. There's a giant pot of honey in your room.");
		yield return new TwineText(@"");
		yield return new TwineText(@"And it's right above your bed.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear climbs on top of your bed which definitely can't take the weight. The bed and bear together fall on you hiding underneath the bed. Like the bed, you couldnn't bear the weight and you expire.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But not quite before you utter ""(print: $epitaph)?"" Inquisitively once more.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Whatever is on the other side of the door, screw fighting it! Luckily there's plenty of room underneath your bed to hide. You drop your sword and clamber underneath.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The growls and snarls continue to grow. Before long your door explodes into splinters and a massive bear comes lumbering into your room.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear lumbers around the room doing a good job in general at messing up the place. Before long the bear notices the chandelier above your bed.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Before you can really react the bear has leapt on your bed to get at the chandelier. The bear is literally jumping on the bed and through that action jumping on your body.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It's extremely painful, but not quite lethal. Then, suddenly, the chandelier falls from the ceiling. The bear dives away, the limber beast. Meanwhile all you can think to say is ""(print: $epitaph)"" right before you are impaled by all manners of chandelier shards.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"Underneath you're bed you're ready for the monster.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Unless it's a bear of course. *Which it absolutely is*. Your front door explodes into splinters and a bear comes barreling into your room.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear sees the other bear trophy above your bed and immediately in a rage moves to tear it down. Rampaging through the room you're little but collateral damage to the bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"As you scream in pain as your life slowly drains away from you you only say to yourself ""(print: $epitaph)"" never quite realizing its meaning.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $action is ""ready"")[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Your front door explodes.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It's a massive grizzly bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You barely have to time to react--""(print: $epitaph)"" you say, almost instinctually.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It's a teleport spell! The world around you crumbles back into a black void and before long is replaced by a cave.");
		yield return new TwineText(@"");
		yield return new TwineText(@"A bear cave.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)"" teleports you to a *bear* cave.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear family inside the bear cave makes immediate work of you before you can even think of another spell to say.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You stand ready. You liberated a kingdom. You can fell any number of foul beasts.");
		yield return new TwineText(@"");
		yield return new TwineText(@"A mighty challenge blasts the door open before you. It's a bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"To your credit, you fight valiantly.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But ultimately a bear is extremely difficult to win against. Even with a sword.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You try your hardest even landing a strike or two. But eventually the bear wins.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear *always* wins.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"Stupidly you decide to stand right in front of your door, pointing your crossbow at whatever comes through.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The door explodes  right in your face as a bear launches into your home. The splintering wood makes it exceedingly difficult to avoid.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear gets you, mauls you, and disposes of you.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You scream, terrified of whatever might come.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Perhaps you should've taken an action because a bear blasts apart your door and charges right at you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Frozen in terror you can do nothing as the bear mauls you to death.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You scream at the top of your lungs hoping anyone can hear you in the castle.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your screams fall on bear ears though because a bear a comes crashing through your door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You have just enough time to put your hand around your sword. But not quite *enough* time to put your sword to any use as the bear grabs and crushes you.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"Your battle-cry is epic.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)!"" you repeat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Whatever is on the other side quiets for a moment.");
		yield return new TwineText(@"");
		yield return new TwineText(@"*A moment*.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Suddenly your door splinters open in an explosion of wood. A bear tumbles in through your door. Furious, cold, and hungry the bear charges at you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"With your crossbow unloaded there is little you can do but accept your fate as this bear's next meal.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"]");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You die ", @"You die ", @" wakeUp", null, null);	
	}
    
	// .............
	// #24:  catAttack

	void passageInit_24()
	{
		this.Passages[" catAttack"] = new TwinePassage(" catAttack", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"(if: $action is ""bed"")[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Suddenly a cat leaps through your window.");
		yield return new TwineText(@"");
		yield return new TwineText(@"While it could be harmless, many of the cats in the magical glade outside are actually quite deadly. In fact, some even sound like bears.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"A cat leaps into your chamber. You love cats, but you're still not sure what the growl was.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"A cat leaps in from the cold.");
		yield return new TwineText(@"");
		yield return new TwineText(@"No way a cat survied out there. But maybe one did and just wanted to be warm?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Regardless, what was that growl.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Crawl Out Of The Bed ", @"Crawl Out Of The Bed ", @" catCrawl01", null, null);
		yield return new TwineLink(@"Stay Hidden Underneath The Bed ", @"Stay Hidden Underneath The Bed ", @" catCrawl02", null, null);
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $action is ""ready"")[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"For minutes nothing else happens. You decide to cautiously open the door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"On your step outside is naught but a cat.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Weapon in hand you cautiously approach your door. Battle ready you await whatever is on the other side.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You suddenly fling your door open to be greeted by a cat before you.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"With one hand on your crossbow ready to fire your other reaches out to open your door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"In front of you is a cat.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Put Your Weapon Down ", @"Put Your Weapon Down ", @" catReady01", null, null);
		yield return new TwineLink(@"Attack The Cat ", @"Attack The Cat ", @" catReady02", null, null);
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You scream and scream and scream.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Before long a cat bounces in through your window.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Does this calm you down or terrify you more?");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Your royal scream was supposed to attract your servants. Instead, it attracted a cat which comes in through your window.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"Your battle-cry has never attracted a cat before, but that is exactly what bounces through the window.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue Screaming ", @"Continue Screaming ", @" catScream01", null, null);
		yield return new TwineLink(@"'Awwwwwwwwwwwwww' ", @"'Awwwwwwwwwwwwww' ", @" catScream02", null, null);
		yield return new TwineText(@"]");	
	}
    
	// .............
	// #25:  hoodedFigure01

	void passageInit_25()
	{
		this.Passages[" hoodedFigure01"] = new TwinePassage(" hoodedFigure01", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"(if: $action is ""ignore"")[");
		yield return new TwineText(@"""(print: $epitaph).""");
		yield return new TwineText(@"");
		yield return new TwineText(@"What? That phrase! Whatever is on the other side is chanting it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)!!!!!!!!!""");
		yield return new TwineText(@"");
		yield return new TwineText(@"Louder.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)!!!!!!!!!""");
		yield return new TwineText(@"");
		yield return new TwineText(@"Louder still.");
		yield return new TwineText(@"");
		yield return new TwineText(@"*(print: $epitaph)*?");
		yield return new TwineText(@"");
		yield return new TwineText(@"The door, as if by magic, seemingly disintigrates. Before you stands a tall hooded figure. Menacing and wraith like.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The figure slowly glides towards you. As he does the environment around you melts into darkness once more.");
		yield return new TwineText(@"");
		yield return new TwineText(@"After but a moment all that remains is the figure who slowly removes their hood.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Beneath the hood is naught by a singular white light which slowly consumes your entire being.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $action is ""door"")[");
		yield return new TwineText(@"You lay your (print: $weapon) on the ground. The knock is calling to you. Wanting to take you home.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You trust it implicitly--not even knowing what's on the other side. It's curiously natural to you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your hand reaches for the door but before you can open the door the knob twists and the door opens on its own. There is nothing in front of you but the black void.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your feeling of trust is immediately lost and you turn to grab your (print: $weapon). Yet it's not there. The entire room has once again faded into blackness entirely.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)""");
		yield return new TwineText(@"");
		yield return new TwineText(@"A voice reaches out to you through the darkness. Repeating (print: $epitaph) repeatedly.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Before long you are repeating (print: $epitaph) along with the voice in the darkness.");
		yield return new TwineText(@"");
		yield return new TwineText(@"And then, suddenly the voice stops but you can't stop saying (print: $epitaph).");
		yield return new TwineText(@"");
		yield return new TwineText(@"Over and over again you say the phrase.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"Not knowing what to expect you peer out the window in the room. The black void peers back.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The door to your room opens with a bang. Out of the corner of your eye you catch a black blur.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You jump back from the window and look for your (print: $weapon). It's nowhere to be found.");
		yield return new TwineText(@"");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Suddenly you begin to rise off the ground.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)"".");
		yield return new TwineText(@"");
		yield return new TwineText(@"You hear the phrase and remember--it's a levitation spell.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You try to fight against the magic and as you struggle you catch sight of a black hooded figure using your trusty staff.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Suddenly your room disappears from sight and you return to the black void still rising infinitely through empty space. The  hooded figure is still visible far beneath you. Instead of black though, they seem to be replaced with a blazign white light.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Suddenly you stop rising and begin to fall through the air.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"]");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your world slowly fades to black as you utter your last words:");
		yield return new TwineText(@"<br>");
		yield return new TwineText(@"<p>");
		yield return new TwineText(@"(print: ""..."" + $epitaph)");
		yield return new TwineText(@"</p>");
		yield return new TwineText(@"");
		yield return new TwineText(@"# ");yield return new TwineLink(@"You Die ", @"You Die ", @" wakeUp", null, null);	
	}
    
	// .............
	// #26:  grandma01

	void passageInit_26()
	{
		this.Passages[" grandma01"] = new TwinePassage(" grandma01", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"A sweet and wise voice rings out to you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)""");
		yield return new TwineText(@"");
		yield return new TwineText(@"There it is! That phrase that has occupied you so. Spoken by... yes, none other than your very own grandmother. How she has gotten here is beyond you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Perhaps it is not what it seems.");
		yield return new TwineText(@"");
		yield return new TwineText(@"(if: $action is ""ignore"")[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"A druid has sworn off contact with their previous family. Yet to see your grandmother once again?");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Your traitorous grandmother almost swung your war of liberation in the wrong direction. Even if it were her, what would you say?");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"It's true what they say about hunters. They all have grandmothers.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Open the door anyway ", @"Open the door anyway ", @" gmaIgnore01", null, null);
		yield return new TwineLink(@"Clutch your (print: $weapon) and prepare to ambush the impostor ", @"Clutch your (print: $weapon) and prepare to ambush the impostor ", @" gmaIgnore02", null, null);
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $action is ""door"")[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Excitedly you race towards the door and fling it open! It's Grandma. Grandma is here!");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Royalty must remain stalwart at all times. But your grandmother was a traitor during the war.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"Yes. It actually *is* your grandmother.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Say Hello to Grandma ", @"Say Hello to Grandma ", @" gmaDoor01", null, null);
		yield return new TwineLink(@"Shut the door in Grandma's face ", @"Shut the door in Grandma's face ", @" gmaDoor02", null, null);
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You see her. Your grandmother. You could sneak up on her to say hello. Or maybe pull a trick on her and tell her to go away only to ambush her with a love spell!");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Your grandmother was a traitor during the war of liberation. Her actions still lay heavy on your mind to this day. Would you confront the woman or sneak out during the night?");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"While it is your grandmother, your seclusion should not be impeded. Would you sneak away or insist that your own grandmother leave?");
		yield return new TwineText(@"]");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Sneak out the window ", @"Sneak out the window ", @" gmaWindow01", null, null);
		yield return new TwineLink(@"Yell out your window ""Go away Grandma!"" ", @"Yell out your window ""Go away Grandma!"" ", @" gmaWindow02", null, null);	
	}
    
	// .............
	// #27:  catCrawl01

	void passageInit_27()
	{
		this.Passages[" catCrawl01"] = new TwinePassage(" catCrawl01", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You crawl out of your bed. It's a cute little kitty!");
		yield return new TwineText(@"");
		yield return new TwineText(@"But it's a kitty with a taste for flesh. The cat roars at you. It turns out that it was a cat that sounds like a bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The cat bites into your neck the second you get near it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You bleed out slowly and painfully.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"The cat's presence coaxes you out of your bed.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Immediately the cat leaps at you and gives you a small bite on your hand.");
		yield return new TwineText(@"");
		yield return new TwineText(@"While not instantly painful, the deed has been done. The cat delivered a poisonous payload. It must have been your traitorous grandmother!");
		yield return new TwineText(@"");
		yield return new TwineText(@"As the poison begins to take its toll and you can only wonder behind the meaning of ""(print: $epitaph)"".");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"You scramble out of your bed immediately. You recognize that this cat represents an incredible danger.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But it's too late. Before your very eyes the cat transforms into a bear and mauls you to death.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #28:  catCrawl02

	void passageInit_28()
	{
		this.Passages[" catCrawl02"] = new TwinePassage(" catCrawl02", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You stay hidden underneath your bed. While a fan of cats, you simply can't trust that this isn't some trap.");
		yield return new TwineText(@"");
		yield return new TwineText(@"*There are cats with the strength of bears in these woods.*");
		yield return new TwineText(@"");
		yield return new TwineText(@"You stay hidden underneath your bed as the cat wanders around the room.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Yet you should've probably chosen a better hiding spot. It is a cat with the strength of a bear. As the cat finally makes its way to your hiding spot it finally spots you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It lumbers after you, letting out a mighty bear like roar. It's too late for you to get out of the way as the bear-cat removes you from existence.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Staying hidden seems smart at first. The cat doesn't *instantly* find you. But it does *eventually.*");
		yield return new TwineText(@"");
		yield return new TwineText(@"At some point during the cat's hunt you realized that it was sent by your traitorous grandmother. Instead of a dragon, this time she sent a cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The cat simply walks up to you and bites you on the nose. The cat's teeth, having been coated in a lethal poison, pierce your skin and deliver the deadly poison.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You slowly die where you lie.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"The cat made a terrible mistake coming in here.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You stay underneath your bed taking aim at the cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Just when you are about to shoot you are distracted though, your door explodes in a splinter of wood. A massive bear was also outside.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The cat runs away in terror. Unfortunately you're stuck underneath your bed and can do nothing as the bear destroys you and your room.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #29:  catScream01

	void passageInit_29()
	{
		this.Passages[" catScream01"] = new TwinePassage(" catScream01", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You continue screaming. You know whatever this animal is, it's no mere cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The screams annoy the animal who changes to reveal their true form. A monstrous bear-cat. The bear cat attacks you to cease your screaming.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Frozen in terror you can do nothing as the bear tears you to pieces.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You continue to scream for help. As your rule of this kingdom continue grew your paranoia over being assassinated only grew.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You fear the cat was sent by your traitorous grandmother. And rightly so.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Yet you should have done something other than scream. Unimpeded the cat leaps at you and bites you on your arm delivering a deadly poison.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Very quickly the poison travels through your body. Paralyzing you (and stopping your screams!). Then the poison slowly drains the life from your body.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"You continue to unleash your mighty battle cry. The cat runs away in terror, hiding in a corner of your room. Afraid.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Satisfied that the danger has passed you lower your weapon. And move towards the cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Before your very eyes the cat transforms into a monstrous bear. Having lowered your weapon there is nothing to defend yourself with and the bear immediately attacks you.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #30:  gmaIgnore01

	void passageInit_30()
	{
		this.Passages[" gmaIgnore01"] = new TwinePassage(" gmaIgnore01", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"GRANDMA!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Then you remember, she *always* called you (print: $epitaph). That's where it came from.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You throw your staff to the side. Overjoyed, you forget your druidic oaths.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You run to open the door when suddenly your brain simply shuts off. Breaking your oaths results in death. You only manage to say ""(print: $epitaph)"" one last time.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Once a traitor always a traitor.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Before you could even raise your sword your grandmother viciously attacks you with a dagger.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Regicide is a serious crime. All you can hope for is that your grandmother finds justice for all her transgressions.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your majesty dies.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"You open the door. You expect your grandmother. It wasn't your grandmother.");
		yield return new TwineText(@"");
		yield return new TwineText(@"No, it was a bear who could speak.");
		yield return new TwineText(@"");
		yield return new TwineText(@"And that bear could say (print: $epitaph).");
		yield return new TwineText(@"");
		yield return new TwineText(@"As an ace hunter you should've known about this species of grandma imitating bears but how could you?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Needless to say the bear mauls you to death.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #31:  gmaIgnore02

	void passageInit_31()
	{
		this.Passages[" gmaIgnore02"] = new TwinePassage(" gmaIgnore02", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"No. It cannot be your grandmother.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You stand ready. A wide variety of magic is at your fingertips and you are ready to go.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The door opens and you unleash a massive spell that propels an inferno of fire towards the front door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"For a nature loving druid you know an exceedingly large amount of fire spells.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But it actually *is* your grandmother.");
		yield return new TwineText(@"");
		yield return new TwineText(@"As your grandmother is engulfed in flames you attempt to save her. However in the act you only end up catching yourself aflame.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You burn not only yourself and your hut but the entire forest as well.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You have decided. Your grandmother is a traitor and must answer for her crimes.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your grandmother flings the door open and brandishes a dagger. She charges at you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You prepare to deflect the attack but your weapon is stuck in its sheathe. You struggle profusely to free it from the sheathe's grasp. But there's no luck.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your grandmother descends upon you with a flurry of stabs. She continuously chants (print: $epitaph) as you bleed out.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"You load your crossbow with a bolt. If it's not your grandmother then you will have a glorious new hunt.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The door opens yet nothing is in the door frame.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Curiously you lower your crossbow. Confused.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Suddenly above you the ceiling bursts open. A massive bear falls from the infinite black void. The bear absolutely crushes you.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #32:  gmaDoor01

	void passageInit_32()
	{
		this.Passages[" gmaDoor01"] = new TwinePassage(" gmaDoor01", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"""HI GRANDMA!!!""");
		yield return new TwineText(@"");
		yield return new TwineText(@"You're so excited to see your grandmother standing there before you. She's absolutely beautiful.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Yet a druid cannot see family from their previous life without paying the ultimate price.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Though unintentional, your Grandmother's mere presence results in a catastrophic heart failure. Unfortunately you collapse to the ground and die.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"""Hello... *grandmother*. Or should I say, traitor!""");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"""Hello Grandma""");
		yield return new TwineText(@"");
		yield return new TwineText(@"You invite your grandmother in. You spend the evening trading stories and together you cook a grand meal.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It seems though in your haste to cook a large meal, you attract a wild bear which comes crashing into your hut. Destroying both you *and* your grandmother in the process.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #33:  gmaDoor02

	void passageInit_33()
	{
		this.Passages[" gmaDoor02"] = new TwinePassage(" gmaDoor02", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Grandma stands before you in the frame of your door.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But you know what you have to do. A druid can't break their oath. The must abandon all past family.");
		yield return new TwineText(@"");
		yield return new TwineText(@"So you shut the door. You hear your grandmother on the other side of the door begin to cry.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)!"" She cries.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The pain is too much for you to bear. You are stuck between two great loves.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You grab your staff. Determined to find a solution. You think of an incantation that might solve your problems.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You prepare a spell to break your oath and reunite you with your grandmother.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your spell is powerful. It draws in the energy from the magical glade around your hut. Yet you can't contain the spell and it explodes.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You instantly notice a dagger in your Grandmother's hand. You shut the door immediately.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your grandmother, the nimble minx that she is, manages to block it with her foot. With incredible leg strength she blasts the door open.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You tumble backwards your sword falling out of your hand.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your traitorous grandmother wastes no time in pressing her advantage and she stabs you to death in a flurry of blades.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"Your Grandma waves to you in the doorway. But behind her a bear is barreling towards your hut.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your hunter instinct is to sacrifice your grandmother. You slam the door shut in her face.");
		yield return new TwineText(@"");
		yield return new TwineText(@"This is actually mostly ineffective. The bear tears through your grandmother like tissue paper. Your hut and own body fare no better.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #34:  gmaWindow01

	void passageInit_34()
	{
		this.Passages[" gmaWindow01"] = new TwinePassage(" gmaWindow01", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You simply can't face your grandmother. A druidic oath binds you to abandon all family.");
		yield return new TwineText(@"");
		yield return new TwineText(@"So you to decide to sneak outside the window.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Unfortunately your grandmother catches you climbing out the window");
		yield return new TwineText(@"");
		yield return new TwineText(@"""(print: $epitaph)!"" she yells out to you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"This family reunion of sorts is just enough for the magical oaths in place to stop your heart. Though it's little solace, you do at least issue your last breaths in the presence of your grandmother.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Royalty shouldn't have to face situations like this.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You climb out your window. Only you forgot that you live at the top of a tower.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It will never be said that you were smart Royalty. But you are definitely *dead* royalty.");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"You can't stand the thought of interrupting your lonely existence.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You slip out the window into the blizzard.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You make it about 30 feet before a bear comes at you through the blizzard. You only have enough time to blink at the bear before you are torn apart by the ferocious beast.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #35:  gmaWindow02

	void passageInit_35()
	{
		this.Passages[" gmaWindow02"] = new TwinePassage(" gmaWindow02", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You stick your head out the window and tell grandma to go away.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You even try to explain to her that you can't have contact with family or else you will die.");
		yield return new TwineText(@"");
		yield return new TwineText(@"""Nonsense, (print: $epitaph)."" she says.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You can only stare at her before the life drains out of your body as the magical oaths take their toll.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You go to the window to yell at your traitor grandma to get out and leave the kingdom alone.");
		yield return new TwineText(@"");
		yield return new TwineText(@"As you prop yourself at the window you peer outside. Your grandmother is hanging below your window though.");
		yield return new TwineText(@"");
		yield return new TwineText(@"She grabs your neck and pulls you out the window high on your castle's tower. You plummet towards the earth.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your grandma yells at you as fall: ""(print: $epitaph)!""");
		yield return new TwineText(@"](else:)[");
		yield return new TwineText(@"You move to the window to tell your grandmother to leave.");
		yield return new TwineText(@"");
		yield return new TwineText(@"As you stick your head out the window a massive bear, seemingly out of nowhere, swipes at your head and takes it clean off.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #36:  catReady01

	void passageInit_36()
	{
		this.Passages[" catReady01"] = new TwinePassage(" catReady01", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"You lower your weapon. It's a harmless kitten? What's the worst that could happen.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Well, the cat could have the strength of a bear for one thing.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The cat wastes no time in capitalizing on your momentary pause. With the strength of a bear the cat rips you to shreds.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Druids should be better with animals.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You lower your weapon. Royalty would never kill a cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"In your moment of weakness the cat leaps at you though and bites you on the arm. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"The mangy animal! You realize the cat must have been sent by your traitorous grandmother. Instead of a dragon, she sent poisonous cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You can feel the poison seep into your veins. Unable to fight it, you slump to the ground and perish.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"A cat is not a suitable target for such a hunter.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You lower your weapon, you simply couldn't bare it to harm a kitten.");
		yield return new TwineText(@"");
		yield return new TwineText(@"But, before your very eyes, the cat transforms. Into a bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The angry creature is now before you in all its glory. Not a mere cat, but a bear-cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear-cat launches itself at you and shreds you to death.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #37:  catReady02

	void passageInit_37()
	{
		this.Passages[" catReady02"] = new TwinePassage(" catReady02", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"Taking no chances you unleash a spell, a ball of flame, at the cat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The cat deftly dodges your spell of fire.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Now enraged, the cat reveals itself to you. A bear-cat--the cat transforms before your very eyes into a bear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"This bear is now very angry at you and charges. You try your best to cast another spell with your staff but you simply aren't able as the bear gets a hold of you and tears you to pieces.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"You realize very quickly the cat was the source of the growl. You also realize that it was likely sent by your grandmother who betrayed you during the war.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You charge the cat with you weapon. Yet the cat is nimble and easily dodges your attack. As you swing past the cat the animal is able to bite your ankle.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You reel in pain. The cat's teeth were definitely spiked with something. Poison. It quickly travels throughout your body. Paralyzing you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Your sword clanks to the ground as the poison slowly takes your life from you.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"You immediately let your bolt fly out of your crossbow.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bolt pierces the kitten instantly killing the poor animal.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You're mortified. A hunter should never kill an innocent animal. You decided immediately to hold a funeral service for the kitten.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You grab a shovel and venture out into the blizzard. You dig a suitable grave for the animal. Upon your return for the cat's body it is nowhere to be seen. Perhaps more alarming though is the wreckage of your hut.");
		yield return new TwineText(@"");
		yield return new TwineText(@"It's been almost destroyed. Sitting in the middle of the wreckage is a bear. You realize what happened to the cat. Unfortunately you're next. You left your crossbow inside your now ruined home.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear sees you almost instantly and barrels after you. You can only run so fast in the snow and the bear quickly catches up and destroys you.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}
    
	// .............
	// #38:  interludeFinal

	void passageInit_38()
	{
		this.Passages[" interludeFinal"] = new TwinePassage(" interludeFinal", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		yield return new TwineText(@"Bears? Grandma? Assassins? Cats?");
		yield return new TwineText(@"");
		yield return new TwineText(@"It's not all what it seems.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You're dead, yes. But is it really clear what (print: $epitaph) means?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You die ", @"You die ", @" wakeUp", null, null);	
	}
    
	// .............
	// #39:  catScream02

	void passageInit_39()
	{
		this.Passages[" catScream02"] = new TwinePassage(" catScream02", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		yield return new TwineText(@"(if: $weapon is ""staff"")[");
		yield return new TwineText(@"The site of the kitten entrances and calms you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Awwwwww. You move to pet the kitten. The kitten stands still until you get very close to the kitten.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The kitten bounces away. You make chase after the kitten. The kitten just keeps running around your room.");
		yield return new TwineText(@"");
		yield return new TwineText(@"The kitten finds its way on a shelf high up in your room. You reach up to get the cat but the cat jumps off! The shelf falls as you try to climb up to it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You fall to the ground landing on your neck and shattering it. You get one last glimpse of the cat before you die.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(elseif: $weapon is ""sword"")[");
		yield return new TwineText(@"Look at the cute you little kitten!");
		yield return new TwineText(@"");
		yield return new TwineText(@"You throw all your cares away. Your mind hearkens back to before you were royalty. Before you saved a kingdom from your traitorous grandmother. When the most important thing in the world to you was your childhood cat. Mittens");
		yield return new TwineText(@"");
		yield return new TwineText(@"Oh, mittens. The best friend you ever had.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You try to coax the cat to letting you pet them. But like any proud cat, the cat wants nothing to do with you. Instead, the cat bites you and runs away.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Upset you decide to lie down. After a couple moments you realize that you feel incredibly weak. You look at your bite and its turned an extremely strange color.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You realize that the cat was most likely sent by your grandmother who knows of your affection for cats. Realizing that you've been poisoned you can only think one last time about ""(print: $epitaph)"" before you die.");
		yield return new TwineText(@"]");
		yield return new TwineText(@"(else:)[");
		yield return new TwineText(@"The sight of the cat causes your gruff loner exterior to melt away. It's a cute little animal.");
		yield return new TwineText(@"");
		yield return new TwineText(@"You move to pet your new friend. But before your very eyes the cat transforms into a mighty bear!");
		yield return new TwineText(@"");
		yield return new TwineText(@"The bear immediately turns on you. *Why would a cat be on the top of a mountain during a blizzard?*");
		yield return new TwineText(@"");
		yield return new TwineText(@"Violently and mercilessly the bear tears you to shreds.");
		yield return new TwineText(@"]");
		yield return new TwineLink(@"Continue ", @"Continue ", @" interludeFinal", null, null);	
	}

}